# TODO: 补充docker compose配置文件
version: "3"
services:
  app:
    restart: always
    build: .
    command: >
      bash -c
      "gunicorn -w4 -b 0.0.0.0:5000 --log-level=debug manage:app"
    volumes:
      - .:/code
      - static-volume:/code/app/static
    expose:
      - "5000"
    depends_on:
      - mysql
    networks:
      - web_network
      - db_network
  mysql:
    image: mysql:5.7
    volumes:
      - /home/ubuntu/mysql/:/var/lib/mysql
    expose:
      - "3306"
    restart: always
    environment: 
    - MYSQL_ROOT_PASSWORD=2020012377
    - MYSQL_DATABASE=thss 
    - TZ=Asia/Shanghai 
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation- server=utf8mb4_unicode_ci']
    networks:
      - db_network
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8000:8001"
    volumes:
      - static-volume:/code/app/static
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static-volume:
